import { IRoles } from "@/Types/Types";

const Roles: IRoles = {
  manager_patriot: [
    "eta",
    "etd",
    "fraht_account",
    "request_date",
    "inside_number",
    "proform_number",
    "order_number",
    "container_number",
    "simple_product_name",
    "delivery_method",
    "provider",
    "importer",
    "direction",
    "conditions",
    "declaration_issue_date",
    "store_name",
    "store_arrive_date",
    "agent",
    "container_type",
    "ready_date",
    "load_date",
    "is_docs",
    "declaration_number",
    "declaration_issue_date",
    "km_to_dist",
    "train_depart_date",
    "train_arrive_date",
  ],
  manager_buyer: [
    "etd",
    "eta",
    "fraht_account",
    "store_arrive_date",
    "conditions",
    "request_date",
    "inside_number",
    "proform_number",
    "order_number",
    "container_number",
    "simple_product_name",
    "delivery_method",
    "provider",
    "importer",
    "direction",
    "store_name",
    "declaration_issue_date",
    "container_type",
    "ready_date",
    "load_date",
    "declaration_number",
    "declaration_issue_date",
    "km_to_dist",
    "train_depart_date",
    "train_arrive_date",
  ],
  head: ["all"],
  manager_int: ["all"],
  manager_sales: [
    "etd",
    "fraht_account",
    "eta",
    "store_arrive_date",
    "conditions",
    //5
    "inside_number",
    "proform_number",
    "order_number",
    "container_number",
    "simple_product_name",
    "declaration_issue_date",
    "direction",
    "store_name",
    "load_date",
    "km_to_dist",
  ],
  manager_treasury: [
    "etd",
    "fraht_account",
    "eta",
    "store_arrive_date",
    //6
    "inside_number",
    "proform_number",
    "order_number",
    "container_number",
    "provider",
    "importer",
    "declaration_issue_date",
    "declaration_number",
  ],
  manager_store: [
    "etd",
    //7
    "fraht_account",
    "eta",
    "store_arrive_date",
    "inside_number",
    "proform_number",
    "order_number",
    "container_number",
    "simple_product_name",
    "direction",
    "store_name",
    "container_type",
    "conditions",
    "declaration_issue_date",
  ],
};

export const checkRole = (role: string | undefined, column_name: string) => {
  if (role && (role === "head" || role === "manager_int")) return true;
  if (role && Roles[role]?.find((col) => col === column_name)) return true;
  return false;
};
