export const colNames: { name: string; key: string; hasFilter: boolean }[] = [
  { name: "Товар", key: "simple_product_name", hasFilter: true },
  { name: "Способ доставки", key: "delivery_method", hasFilter: true },
  { name: "Поставщик", key: "providers", hasFilter: true },
  { name: "Импортер", key: "importers", hasFilter: true },
  { name: "Условия поставки", key: "conditions", hasFilter: true },
  { name: "Направление", key: "direction", hasFilter: true },
  { name: "Склад", key: "store_name", hasFilter: true },
  { name: "Агент", key: "agent", hasFilter: true },
  { name: "Тип контейенра", key: "container_type", hasFilter: true },
  { name: "Место отправки", key: "place_of_dispatch", hasFilter: true },
  { name: "Линия", key: "line", hasFilter: true },
  { name: "Дата готовности", key: "ready_date", hasFilter: true },
  { name: "Дата загрузки", key: "load_date", hasFilter: true },
  { name: "ETD", key: "etd", hasFilter: true },
  { name: "ETA", key: "eta", hasFilter: true },
  { name: "Релиз", key: "release", hasFilter: true },
  { name: "BL/СМГС/CMR", key: "bl_smgs_cmr", hasFilter: true },
  { name: "ТД", key: "td", hasFilter: true },
  { name: "Дата ДО", key: "date_do", hasFilter: true },
  { name: "Порт", key: "port", hasFilter: true },
  { name: "Д/С для подачи", key: "is_ds", hasFilter: true },
  { name: "Фрахтовый счет", key: "fraht_account", hasFilter: true },
  { name: "Документы для подачи", key: "is_docs", hasFilter: false },
  { name: "Номер декларации", key: "declaration_number", hasFilter: true },
  {
    name: "Дата выпуска декларации",
    key: "declaration_issue_date",
    hasFilter: true,
  },
  { name: "Наличие ОБ", key: "availability_of_ob", hasFilter: true },
  { name: "Ответ ОБ", key: "answer_of_ob", hasFilter: true },
  { name: "Экспедитор", key: "expeditor", hasFilter: true },
  { name: "Станция прибытия", key: "destination_station", hasFilter: true },
  { name: "Осталось км до ст. назначения", key: "km_to_dist", hasFilter: true },
  { name: "Дата отправки по ЖД", key: "train_depart_date", hasFilter: true },
  { name: "Дата прибытия по ЖД", key: "train_arrive_date", hasFilter: true },
  { name: "Автовывоз", key: "pickup", hasFilter: true },
  { name: "Дата прибытия на склад", key: "store_arrive_date", hasFilter: true },
  { name: "Сток Сдачи", key: "stock_place_name", hasFilter: true },
  { name: "Комментарий", key: "comment", hasFilter: false },
];
